version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Preparing output..."
      - mkdir -p output
      - cp -r * output/
      - ls -la output

artifacts:
  files:
    - '**/*'
  base-directory: output

