version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
  
  
    build:
      commands:
        - echo "Packaging build artifacts..."
        - mkdir -p output
        - cp -r !("output") output/  # exclude output folder itself

artifacts:
  files:
    - '**/*'
  base-directory: output
