version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build complete. Preparing artifact..."
      - mkdir -p build
      - cp -r * build/

artifacts:
  files:
    - '**/*'
  base-directory: build

